default:
  cache:
    - key:
        prefix: 'global'
        files:
          - package-lock.json
      paths:
        - node_modules/
      policy: pull
    - key: ${CI_COMMIT_REF_SLUG}
      paths:
        - .npm/
        - dist/

stages:
  - setup
  - security
  - quality
  - release

install:
  stage: setup
  cache:
    - key: ${CI_COMMIT_REF_SLUG}
      paths:
        - .npm
    - key:
        prefix: 'global'
        files:
          - package-lock.json
      paths:
        - node_modules/
      policy: pull-push
  script:
    - npm ci --include=dev --include=optional --no-audit --cache .npm --prefer-offline
  interruptible: true

audit:
  stage: security
  script:
    - npm audit --omit dev; npm audit signatures
  interruptible: true
  allow_failure: true

lint:
  stage: quality
  script:
    - npm run lint
  interruptible: true

build:
  stage: quality
  script:
    - npm run build
  interruptible: true

release:
  stage: release
  variables:
    GITLAB_NPM_HOST: '${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/'
  script:
    - npm config set --location=project "@igo2:registry" https://${GITLAB_NPM_HOST}
    - npm config set --location=project //${GITLAB_NPM_HOST}:_authToken=${GITLAB_TOKEN}
    - npx semantic-release
  only:
    - next
    - preprod
    - main
